; Generated by tools/extract-world.mjs; do not edit.
; Rules: recovered BASIC fc90c8e, DATA 408-418.
; Prose: BASIC 4c9db58, lines 26-97 and 425-455.
; Dynamic sonic, ladder, oxygen and echo output must be supplied by runtime.
HR1:
    DB "You are in your space yacht, which is docked with the giant space wreck."
    DB " To the north is an air-lock. It is open.",0
HR2:
    DB "You have entered the docking bay of the cruiser. The area is dimly lit b"
    DB "y light from distant stars. The air-lock has closed and the electronic l"
    DB "ock has engaged. A passage leads east.",0
HR3:
    DB "Several corridors intersect here. Strewn around the floor are pieces of "
    DB "broken machinery. The corridor is lit by the emergency lamps, forever dr"
    DB "awing their power from the solar stacks.",0
HR4:
    DB "Several corridors intersect here. Some cables have been severed and are "
    DB "hanging, dangerously, from the ceiling.",0
HR5:
    DB "You are in a small observation port. The north and west walls are made o"
    DB "f a glass-like material. It is showing signs of stress.",0
HR6:
    DB "You are in a service tunnel. Someone has ripped the cables and equipment"
    DB " from the walls and mangled them.",0
HR7:
    DB "You are in a service tunnel. A pool of oil is on the floor.",0
HR8:
    DB "This is a main corridor junction.",0
HR9:
    DB "You are in an observation port. Through the eastern wall you can see the"
    DB " distant emery nebula.",0
HR10:
    DB "Now you are in an access chamber. To the north is a flimsy ladder leadin"
    DB "g upwards.",0
HR11:
    DB "You are on the ladder in a plexiglass observation tube, which is used to"
    DB " service the stabilizer retros.",0
HR12:
    DB "You are standing at the top of a ladder. A passage leads south.",0
HR13:
    DB "Equipment lines the walls. This room is the relay station between the up"
    DB "per and lower decks of the cruiser.",0
HR14:
    DB "You are in a dark room. To the west is a room marked 'Transmat'.",0
HR15:
    DB "You are in a long, dimly lit passage. The air smells of ozone.",0
HR16:
    DB "You are standing in a small metal bay. In front of you are several compu"
    DB "ter banks one of them bearing the word . Transmat.",0
HR17:
    DB "This is an escape pod. To activate it you need to know a secret code",0
HR18:
    DB "Before you looms one of the cruiser's warp engines. It is undamaged.",0
HR19:
    DB "You are in the maintenance workshop.",0
HR20:
    DB "The warp engine stretches away to the south.",0
HR21:
    DB "You are in a long, dark corridor.",0
HR22:
    DB "You are in a long, dark corridor.",0
HR23:
    DB "You are in a long, dark corridor.",0
HR24:
    DB "You are in a long, dark corridor.",0
HR25:
    DB "You are in a long, dark corridor.",0
HR26:
    DB "You are in a corridor junction.",0
HR27:
    DB "You are in a small room. There is no way out.",0
HR28:
    DB "You are on a ledge overlooking a deep shaft.",0
HR29:
    DB "You are in a corridor junction.",0
HR30:
    DB "You are on the bridge of the cruiser.",0
HR31:
    DB "You are on the bridge. Before you is a large chart.",0
HR32:
    DB "The manual controls of the cruiser line the walls.",0
HR33:
    DB "You are in a corridor junction. Before you is a small computer terminal "
    DB "labelled . Flight computer. It seems too small for such a task. Some of "
    DB "its circuit cards are missing.",0
HR34:
    DB "The warp engine stretches away to the south.",0
HR35:
    DB "Before you looms a warp engine. It has been burnt out.",0
HR36:
    DB "You are in a corridor junction.",0
HR37:
    DB "Here the main corridor ends. From it branch three access tunnels.",0
HR38:
    DB "You are crawling through a long, dark wiring conduit. The surfaces are c"
    DB "overed in sharp rivets that make crawling agonizing.",0
HR39:
    DB "Before you looms one of the warp engines. It stretches away to the north"
    DB ".",0
HR40:
    DB "You are in a long east-west access tunnel.",0
HR41:
    DB "You are in a corridor junction.",0
HR42:
    DB "You are in a corridor junction. You are walking in circles.",0
HR43:
    DB "You are at another corridor junction.",0
HR44:
    DB "You are in a corridor junction.",0
HR45:
    DB "The corridors are changing before your very eyes!",0
HR46:
    DB "You are in an endless passage. The silence is terrifying. .",0
HR47:
    DB "You are standing in an acoustically sealed room.",0
HR48:
    DB "Before you is an electronic mine field. . One false step will be fatal.",0
HR49:
    DB "You survived the mine field and have stumbled into a dimensional warp. N"
    DB "othing appears to be where it is. A passage leads south.",0
HR50:
    DB "You have penetrated the computer complex.",0
HR51:
    DB "There is a heavy iron door to the north.",0
HR52:
    DB "You are in a long dimly lit passage.",0
HR53:
    DB "You are in a small observation bubble. From here you can see your yacht "
    DB "in the docking bay. The damage to the yacht appears to be minor",0
HR54:
    DB "You are in a long dimly lit passage. There is a body on the floor. It ha"
    DB "s been shot.",0
