; Generated by tools/extract-world.mjs; do not edit.
; Rules: recovered BASIC fc90c8e, DATA 408-418.
; Prose: BASIC 4c9db58, lines 26-97 and 425-455.
; Room entries are indexed from room 1; directions N,S,W,E.
h_exits:
    DB 2,0,0,0
    DB 128,0,128,3
    DB 5,6,2,4
    DB 3,0,3,8
    DB 128,4,128,9
    DB 0,0,3,7
    DB 8,0,6,0
    DB 9,7,10,9
    DB 10,8,5,128
    DB 11,0,5,9
    DB 12,10,128,128
    DB 11,36,17,17
    DB 15,14,0,0
    DB 13,0,16,51
    DB 13,31,26,26
    DB 26,0,29,14
    DB 0,0,0,0
    DB 0,20,19,0
    DB 0,0,0,18
    DB 18,39,0,21
    DB 22,0,20,0
    DB 53,21,0,23
    DB 0,0,22,36
    DB 0,0,36,25
    DB 28,0,24,35
    DB 0,26,15,15
    DB 0,0,0,0
    DB 129,0,0,0
    DB 0,52,0,16
    DB 0,0,128,31
    DB 0,15,30,32
    DB 0,33,0,31
    DB 32,0,0,128
    DB 35,39,0,0
    DB 0,34,25,0
    DB 37,12,23,24
    DB 36,38,38,38
    DB 37,39,39,39
    DB 37,0,40,40
    DB 0,0,39,39
    DB 46,42,41,41
    DB 41,41,43,43
    DB 41,44,42,42
    DB 45,42,46,46
    DB 46,44,46,47
    DB 41,41,42,42
    DB 0,48,45,0
    DB 47,49,45,0
    DB 50,0,0,48
    DB 49,0,0,0
    DB 0,54,14,0
    DB 29,53,0,0
    DB 0,22,0,0
    DB 51,27,0,0
H_INIT:
    DB 5,36,42,16,52,25,37,1,26,50,50,33,21,41,19,9,27,2,19,7,12,40,34,17
h_rooms:
    DW HR1
    DW HR2
    DW HR3
    DW HR4
    DW HR5
    DW HR6
    DW HR7
    DW HR8
    DW HR9
    DW HR10
    DW HR11
    DW HR12
    DW HR13
    DW HR14
    DW HR15
    DW HR16
    DW HR17
    DW HR18
    DW HR19
    DW HR20
    DW HR21
    DW HR22
    DW HR23
    DW HR24
    DW HR25
    DW HR26
    DW HR27
    DW HR28
    DW HR29
    DW HR30
    DW HR31
    DW HR32
    DW HR33
    DW HR34
    DW HR35
    DW HR36
    DW HR37
    DW HR38
    DW HR39
    DW HR40
    DW HR41
    DW HR42
    DW HR43
    DW HR44
    DW HR45
    DW HR46
    DW HR47
    DW HR48
    DW HR49
    DW HR50
    DW HR51
    DW HR52
    DW HR53
    DW HR54
H_NAMES:
    DW HO1
    DW HO2
    DW HO3
    DW HO4
    DW HO5
    DW HO6
    DW HO7
    DW HO8
    DW HO9
    DW HO10
    DW HO11
    DW HO12
    DW HO13
    DW HO14
    DW HO15
    DW HO16
    DW HO17
    DW HO18
    DW HO19
    DW HO20
    DW HO21
    DW HO22
    DW HO23
    DW HO24
HO1:
    DB "service drone",0
HO2:
    DB "dilapidated 'droid",0
HO3:
    DB "battered humanoid",0
HO4:
    DB "security machine",0
HO5:
    DB "rusty drone",0
HO6:
    DB "old robot",0
HO7:
    DB "fuel pump",0
HO8:
    DB "compass",0
HO9:
    DB "bomb",0
HO10:
    DB "computer memory",0
HO11:
    DB "computer processor",0
HO12:
    DB "computer tape",0
HO13:
    DB "interesting book",0
HO14:
    DB "stabilizer servo",0
HO15:
    DB "toolkit",0
HO16:
    DB "digital clock",0
HO17:
    DB "transmat bracelet",0
HO18:
    DB "box of matches",0
HO19:
    DB "sonic screwdriver",0
HO20:
    DB "hand-held blaster",0
HO21:
    DB "gas mask",0
HO22:
    DB "thin and tatty rope",0
HO23:
    DB "small magnet",0
HO24:
    DB "small fuse",0
