import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const ORIGINAL = 'fc90c8e';
export const PROSE = '4c9db58';
export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export function sourceAt(revision, root = ROOT) {
  return execFileSync('git', ['show', `${revision}:src/hyperdrive.bas`], { cwd: root, encoding: 'utf8' });
}
export function extractNumeric(source) {
  const values = source.split(/\r?\n/).flatMap(line => {
    const match = line.match(/^(\d+)\s+data\s*(.*)$/i);
    if (!match || +match[1] < 408 || +match[1] > 418) return [];
    if (!/^\s*\d+(?:\s*,\s*\d+)*\s*$/.test(match[2])) throw Error('Invalid numeric DATA');
    return match[2].split(',').map(Number);
  });
  if (values.length !== 240) throw Error(`Expected 240 numeric DATA entries; got ${values.length}`);
  const objects = values.slice(0, 24);
  const exits = Array.from({ length: 54 }, (_, room) => values.slice(24 + room * 4, 28 + room * 4));
  if (objects.some(value => value < 1 || value > 54)) throw Error('Invalid initial object location');
  if (exits.flat().some(value => value > 54 && ![128, 129, 130].includes(value))) throw Error('Invalid exit destination');
  return { objects, exits };
}
function conditionMatches(condition, room) {
  return condition.split(/\s+or\s+/i).some(part => part.split(/\s+and\s+/i).every(term => {
    const match = term.trim().match(/^a\s*(=|<|>)\s*(\d+)$/i);
    if (!match) throw Error(`Unsupported room predicate: ${term}`);
    return match[1] === '=' ? room === +match[2] : match[1] === '<' ? room < +match[2] : room > +match[2];
  }));
}
// BASIC 88-92 sonic exposure, 109-115 ladder/oxygen and 476-485 echo
// belong to runtime state. Do not freeze their conditional output into rooms.
export function extractRooms(source) {
  const assignments = source.split(/\r?\n/).flatMap(line => {
    const match = line.match(/^(\d+)\s+(?:if\s+(.*?)\s+then\s+)?g\$\s*=\s*(g\$\s*\+\s*)?"([^"]*)"\s*$/i);
    if (!match || +match[1] < 26 || +match[1] > 97 || /p\(/i.test(match[2] || '')) return [];
    return [{ line: +match[1], condition: match[2], append: !!match[3], text: match[4] }];
  });
  if (!assignments.some(value => value.line === 26)) throw Error('Missing default room description');
  return Array.from({ length: 54 }, (_, index) => {
    let text = '';
    for (const assignment of assignments) {
      if (assignment.condition && !conditionMatches(assignment.condition, index + 1)) continue;
      text = (assignment.append ? text : '') + assignment.text;
    }
    // Remove recovered screen-clear punctuation, retain words and sentence punctuation.
    return text.replace(/^\.+\s*/, '').replace(/\.\s*\.\s*/g, '. ').replace(/\s+/g, ' ').trim();
  });
}
export function extractObjectNames(source) {
  const words = source.split(/\r?\n/).flatMap(line => {
    const match = line.match(/^(40[0-7])\s+data\s+(.*)$/i);
    return match ? match[2].split(',').map(word => word.trim().replace(/^"|"$/g, '')) : [];
  }).slice(0, 24);
  if (words.length !== 24) throw Error('Expected 24 object names');
  // Adjectives are from BASIC 430-453; grammatical articles are supplied by the renderer.
  const prefixes = ['service ', 'dilapidated ', 'battered ', 'security ', 'rusty ', 'old ', 'fuel ', '', '', 'computer ', 'computer ', 'computer ', 'interesting ', 'stabilizer ', '', 'digital ', 'transmat ', 'box of ', 'sonic ', 'hand-held ', 'gas ', 'thin and tatty ', 'small ', 'small '];
  return words.map((word, index) => prefixes[index] + word);
}
function asmText(label, text) {
  if (!/^[\x20-\x7e]+$/.test(text) || text.includes('"')) throw Error(`Non-ASCII or quoted text: ${label}`);
  const chunks = text.match(/.{1,72}/g);
  return `${label}:\n` + chunks.map((chunk, index) => `    DB "${chunk}"${index === chunks.length - 1 ? ',0' : ''}`).join('\n');
}
export function generate(root = ROOT) {
  const numeric = extractNumeric(sourceAt(ORIGINAL, root));
  const prose = sourceAt(PROSE, root);
  const rooms = extractRooms(prose);
  const names = extractObjectNames(prose);
  const header = `; Generated by tools/extract-world.mjs; do not edit.\n; Rules: recovered BASIC ${ORIGINAL}, DATA 408-418.\n; Prose: BASIC ${PROSE}, lines 26-97 and 425-455.\n`;
  const world = header + '; Room entries are indexed from room 1; directions N,S,W,E.\nh_exits:\n' + numeric.exits.map(row => '    DB ' + row.join(',')).join('\n') + '\nH_INIT:\n    DB ' + numeric.objects.join(',') + '\nh_rooms:\n' + rooms.map((_, index) => `    DW HR${index + 1}`).join('\n') + '\nH_NAMES:\n' + names.map((_, index) => `    DW HO${index + 1}`).join('\n') + '\n' + names.map((name, index) => asmText(`HO${index + 1}`, name)).join('\n') + '\n';
  const roomtext = header + '; Dynamic sonic, ladder, oxygen and echo output must be supplied by runtime.\n' + rooms.map((room, index) => asmText(`HR${index + 1}`, room)).join('\n') + '\n';
  for (const [name, text] of [['world.asm', world], ['roomtext.asm', roomtext]]) {
    if (text.split('\n').length > 500) throw Error(`${name} exceeds 500 lines`);
    mkdirSync(path.join(root, 'cpm'), { recursive: true });
    writeFileSync(path.join(root, 'cpm', name), text);
  }
  return { ...numeric, rooms, names };
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) generate();
